### ISSUE TITLE
[1차 과제] Todo 앱을 Interface로 설계 및 모델링

### ISSUE THREAD

**Issue by leezer94** [leezer94/wanted-pre-onboarding-challenge-fe-2#6]
- [x] 필요한 데이터를 모두 TypeScript's Interface로 모델링한다.
- [x] 사용되는 모든 함수를 `선언부만` 만든다.
- [x] 함수 및 클래스의 내부는 구현하지 않습니다.
- [x] **Interface만을 따라 작성한 코드가 동작하는 애플리케이션이 되도록 유도하셔야합니다.**

### Todo

```js
Todo {
  아이디(required),
  내용(required),
  완료여부(required),
  카테고리(required),
  태그들(optional),
}
```

### CREATE

- [x] 할 일을 추가할 수 있다.
- [x] 내용없이 추가할 수 없다.

### READ

- [x] 모든 할 일을 조회할 수 있다.
- [x] ID를 기반으로 특정 할 일을 조회할 수 있다.

### UPDATE

- [x] ID를 제외한 모든 속성을 수정할 수 있다.
- [x] 특정 할 일의 특정 태그를 수정할 수 있다.

### DELETE

- [x] ID를 기반으로 특정 할 일을 삭제할 수 있다.
- [x] 모든 할 일을 제거할 수 있다.
- [x] 특정 할 일의 특정 태그를 삭제할 수 있다.
- [x] 특정 할 일의 모든 태그를 제거할 수 있다.

### Modeling (Shape)

```js
Item {
  property(required),
  property(optional),
}
```
